name: secret-detection

on:
  pull_request:
    branches:
      - 'dev'
    types: [opened, reopened]

jobs:
  secret-detection:
    runs-on: self-hosted
      
    steps:

      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install necessary packages
        run: |
          sudo apt-get update
          sudo apt-get install -y python3-pip jq
          pip3 install git+https://github.com/NASA-AMMOS/slim-detect-secrets.git@exp

      - name: Create an initial .secrets.baseline if .secrets.baseline does not exist
        run: |
          if [ ! -f .secrets.baseline ]; then
            echo "⚠️ No existing .secrets.baseline file detected. Creating a new blank baseline file."
            mkdir empty-dir
            /home/asapre/.local/bin/detect-secrets scan empty-dir > .secrets.baseline
            echo "✅ Blank .secrets.baseline file created successfully."
            rm -r empty-dir
          else
            echo "✅ Existing .secrets.baseline file detected. No new baseline file will be created."
          fi

      - name: Scan repository for secrets
        run: |
          cp .secrets.baseline .secrets.new
          /home/asapre/.local/bin/detect-secrets scan --baseline .secrets.new --exclude-files '.secrets.*' --exclude-files 'vars.yaml' --exclude-files '.git*' --exclude-files '.*.js'

          compare_secrets() { diff <(jq -r '.results | keys[] as $key | "\($key),\(.[$key] | .[] | .hashed_secret)"' "$1" | sort) <(jq -r '.results | keys[] as $key | "\($key),\(.[$key] | .[] | .hashed_secret)"' "$2" | sort) >/dev/null; }
          
          cat .secrets.new
          
          if ! compare_secrets .secrets.baseline .secrets.new; then
            echo "⚠️ Attention Required! ⚠️" >&2
            echo "New secrets have been detected in your recent commit. Due to security concerns, we cannot display detailed information here and we cannot proceed until this issue is resolved." >&2
            echo "" >&2
            echo "Please follow the steps below on your local machine to reveal and handle the secrets:" >&2
            echo "" >&2
            echo "1️⃣ Run the 'detect-secrets' tool on your local machine. This tool will identify and clean up the secrets. You can find detailed instructions at this link: https://nasa-ammos.github.io/slim/continuous-testing/starter-kits/#detect-secrets" >&2
            echo "" >&2
            echo "2️⃣ After cleaning up the secrets, commit your changes and re-push your update to the repository." >&2
            echo "" >&2
            echo "Your efforts to maintain the security of our codebase are greatly appreciated!" >&2
            exit 1
          fi
