name: Security Check

on:
  pull_request:
    branches:
      - 'dev'
    types: [opened, reopened]


jobs:
  security_audit:
    runs-on: self-hosted
    defaults:
      run:
        working-directory: /home/asapre/actions-runner/_work/csc-519-project/csc-519-project/coffee-project-main/
    strategy:
      matrix:
        node-version: [18.x, 20.x]

    steps:
      - name: Check out repository code
        uses: actions/checkout@v3

      - name: List files in the repository
        run: ls -la ${{ github.workspace }}

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
            node-version: ${{ matrix.node-version }}
            cache: 'npm'
            cache-dependency-path: 'coffee-project-main/package-lock.json'

      - name: Install dependencies
        run: npm ci
      
      - name: Run Security Audit
        run: npm audit
